// GENERATED by desktop/scripts/build-renderer-lib.sh — do not edit.
// Source: desktop/renderer/src/desktop-bridge.ts
(function () {
const DESKTOP_BRIDGE_VERSION = "1.0.0-alpha.7";
function defineTypedRoute(bridgeMethod, routeID, method, path, body, contentType) {
    return { bridgeMethod, routeID, method, path, body, contentType };
}
// Kept as direct declarations so the boundary checker can compare every typed
// facade method with the authoritative Desktop route manifest.
const ROUTES = {
    authStatus: defineTypedRoute("auth.status", "auth.status", "GET", "/auth/status", "none", null),
    authUserInfo: defineTypedRoute("auth.userInfo", "auth.userinfo", "GET", "/auth/userinfo", "none", null),
    authLogout: defineTypedRoute("auth.logout", "auth.logout", "POST", "/auth/logout", "none", null),
    historyListThreads: defineTypedRoute("history.listThreads", "agent.threads", "GET", "/agent/threads", "none", null),
    historyListMessages: defineTypedRoute("history.listMessages", "agent.thread-messages", "GET", "/agent/threads/:uuid/messages", "none", null),
    agentListSkills: defineTypedRoute("agent.listSkills", "agent.skills.catalog", "GET", "/agent/skills/catalog", "none", null),
    agentListModes: defineTypedRoute("agent.listModes", "agent.skills.modes", "GET", "/agent/skills/modes", "none", null),
    agentCreateThread: defineTypedRoute("agent.createThread", "agent.thread-put", "PUT", "/agent/threads/:uuid", "json", "application/json"),
    agentDeleteThread: defineTypedRoute("agent.deleteThread", "agent.thread-delete", "DELETE", "/agent/threads/:uuid", "none", null),
    agentStartTurn: defineTypedRoute("agent.startTurn", "agent.chat", "POST", "/agent/chat", "json", "application/json"),
    agentListRecoverableTurns: defineTypedRoute("agent.listRecoverableTurns", "agent.turns-recoverable", "GET", "/agent/turns/recoverable", "none", null),
    agentResumeTurn: defineTypedRoute("agent.resumeTurn", "agent.turn-replay", "POST", "/agent/turns/:uuid/replay", "none", null),
    agentCancelTurn: defineTypedRoute("agent.cancelTurn", "agent.turn-cancel", "POST", "/agent/turns/:uuid/cancel", "none", null),
    systemHealth: defineTypedRoute("system.health", "health.get", "GET", "/health", "none", null),
    systemDiagnostics: defineTypedRoute("system.diagnostics", "system.diagnostics", "GET", "/system/diagnostics", "none", null),
    systemServerVersion: defineTypedRoute("system.serverVersion", "system.server-version", "GET", "/system/server-version", "none", null),
    systemTriggerSync: defineTypedRoute("system.triggerSync", "system.trigger-sync", "POST", "/system/trigger-sync", "none", null),
    systemWriteLog: defineTypedRoute("system.writeLog", "system.log", "POST", "/system/log", "json", "application/json"),
    settingsGetModelRoute: defineTypedRoute("settings.getModelRoute", "settings.model-route.get", "GET", "/settings/model-route", "none", null),
    settingsPutModelRoute: defineTypedRoute("settings.putModelRoute", "settings.model-route.put", "PUT", "/settings/model-route", "json", "application/json"),
    agentUploadThreadFile: defineTypedRoute("agent.uploadThreadFile", "agent.thread-file-upload", "POST", "/agent/threads/:uuid/files", "multipart", null),
    agentListThreadFiles: defineTypedRoute("agent.listThreadFiles", "agent.thread-file-list", "GET", "/agent/threads/:uuid/files", "none", null),
};
const JSON_BODY_LIMITS = {
    "agent.createThread": 4 << 10,
    "agent.startTurn": 1 << 20,
    "system.writeLog": 65_536,
    "settings.putModelRoute": 8 << 10,
};
function createDesktopBridge(deps) {
    return {
        version: DESKTOP_BRIDGE_VERSION,
        runtime: { ...deps.runtime },
        capabilities: buildCapabilities,
        auth: {
            status: () => execute(deps, ROUTES.authStatus),
            userInfo: () => execute(deps, ROUTES.authUserInfo),
            beginLogin: () => deps.beginLogin(),
            loginStatus: () => deps.loginStatus(),
            submitLoginPassword: (input) => deps.submitLoginPassword(input),
            cancelLogin: () => deps.cancelLogin(),
            logout: () => execute(deps, ROUTES.authLogout),
        },
        history: {
            listThreads: async (options) => {
                const path = buildListThreadsPath(options);
                return execute(deps, ROUTES.historyListThreads, path);
            },
            listMessages: async (options) => {
                const path = buildListMessagesPath(options);
                return execute(deps, ROUTES.historyListMessages, path);
            },
        },
        agent: {
            listSkills: () => execute(deps, ROUTES.agentListSkills),
            listModes: () => execute(deps, ROUTES.agentListModes),
            deleteThread: async (threadUUID) => {
                const uuid = validateCanonicalV4UUID(threadUUID, "deleteThread threadUUID");
                const path = ROUTES.agentDeleteThread.path.replace(":uuid", encodeURIComponent(uuid));
                return execute(deps, ROUTES.agentDeleteThread, path);
            },
            createThread: async (input) => {
                const request = buildAgentCreateThreadRequest(input);
                const path = ROUTES.agentCreateThread.path.replace(":uuid", encodeURIComponent(request.threadUUID));
                const result = await execute(deps, ROUTES.agentCreateThread, path, request.body);
                return validateAgentCreateThreadResult(result, request);
            },
            uploadThreadFile: async (threadUUID, file) => {
                const uuid = validateCanonicalV4UUID(threadUUID, "agent.uploadThreadFile threadUUID");
                if (!(file instanceof File)) {
                    throw new TypeError("agent.uploadThreadFile file must be a File");
                }
                const path = ROUTES.agentUploadThreadFile.path.replace(":uuid", encodeURIComponent(uuid));
                const formData = new FormData();
                formData.append("file", file, file.name);
                const result = await executeMultipart(deps, ROUTES.agentUploadThreadFile, path, formData);
                return validateAgentThreadFileUploadResult(result);
            },
            // The attachments already on a thread. Uploads persist, but until this
            // existed nothing could read them back, so reopening a thread showed no
            // sources even though the files were on disk and still usable as model
            // context.
            listThreadFiles: async (threadUUID) => {
                const uuid = validateCanonicalV4UUID(threadUUID, "agent.listThreadFiles threadUUID");
                const path = ROUTES.agentListThreadFiles.path.replace(":uuid", encodeURIComponent(uuid));
                return execute(deps, ROUTES.agentListThreadFiles, path);
            },
            listRecoverableTurns: async () => {
                const result = await execute(deps, ROUTES.agentListRecoverableTurns);
                return validateAgentRecoverableTurnListResult(result);
            },
            startTurn: (input, callback) => {
                const request = buildAgentSidecarTurnRequest(input, callback);
                const body = JSON.stringify(request);
                if (new TextEncoder().encode(body).byteLength >
                    JSON_BODY_LIMITS["agent.startTurn"]) {
                    throw new RangeError(`agent.startTurn request body exceeds ${JSON_BODY_LIMITS["agent.startTurn"]} bytes`);
                }
                return deps.startAgentTurn(request, callback);
            },
            resumeTurn: (turnUUID, callback) => {
                if (typeof callback !== "function") {
                    throw new TypeError("agent.resumeTurn callback must be a function");
                }
                return deps.resumeAgentTurn(validateCanonicalV4UUID(turnUUID, "agent.resumeTurn turnUUID"), callback);
            },
            cancelTurn: (turnID) => deps.cancelAgentTurn(validateTurnID(turnID)),
        },
        system: {
            health: () => execute(deps, ROUTES.systemHealth),
            diagnostics: () => execute(deps, ROUTES.systemDiagnostics),
            serverVersion: () => execute(deps, ROUTES.systemServerVersion),
            triggerSync: async (options) => {
                const path = buildTriggerSyncPath(options);
                return execute(deps, ROUTES.systemTriggerSync, path);
            },
            writeLog: async (entry) => {
                validateRendererLogInput(entry);
                return execute(deps, ROUTES.systemWriteLog, undefined, entry);
            },
            revealDataDir: () => deps.revealDataDir(),
        },
        settings: {
            getModelRoute: async () => {
                const result = await execute(deps, ROUTES.settingsGetModelRoute);
                return validateModelRouteSettingsResult(result);
            },
            putModelRoute: async (input) => {
                const body = buildModelRouteSettingsPut(input);
                const result = await execute(deps, ROUTES.settingsPutModelRoute, undefined, body);
                return validateModelRouteSettingsResult(result);
            },
        },
    };
}
function buildCapabilities() {
    return {
        bridgeVersion: DESKTOP_BRIDGE_VERSION,
        compatibility: {
            legacyGlobal: "workmaxLocal",
            legacyFetch: true,
        },
        namespaces: {
            auth: {
                supported: true,
                methods: [
                    "status",
                    "userInfo",
                    "beginLogin",
                    "loginStatus",
                    "submitLoginPassword",
                    "cancelLogin",
                    "logout",
                ],
            },
            history: {
                supported: true,
                methods: ["listThreads", "listMessages"],
            },
            system: {
                supported: true,
                methods: [
                    "health",
                    "diagnostics",
                    "serverVersion",
                    "triggerSync",
                    "writeLog",
                    "revealDataDir",
                ],
                deferred: ["networkState"],
            },
            agent: {
                supported: true,
                methods: [
                    "listSkills",
                    "createThread",
                    "uploadThreadFile",
                    "listRecoverableTurns",
                    "startTurn",
                    "resumeTurn",
                    "cancelTurn",
                ],
                deferred: ["artifact"],
            },
            settings: {
                supported: true,
                methods: ["getModelRoute", "putModelRoute"],
            },
            artifact: {
                supported: false,
                methods: [],
                reason: "artifact-routes-unavailable",
            },
        },
    };
}
function buildModelRouteSettingsPut(input) {
    assertPlainObject(input, "settings.putModelRoute input");
    assertAllowedKeys(input, ["preferred_route", "local"], "settings.putModelRoute input");
    const route = input.preferred_route;
    if (route !== "local" && route !== "official") {
        throw new TypeError('settings.putModelRoute preferred_route must be "local" or "official"');
    }
    const body = { preferred_route: route };
    if (input.local === undefined) {
        return body;
    }
    assertPlainObject(input.local, "settings.putModelRoute local");
    assertAllowedKeys(input.local, ["protocol", "base_url", "model_id", "api_key", "clear_api_key"], "settings.putModelRoute local");
    const protocol = input.local.protocol;
    if (protocol !== "openai_compatible" &&
        protocol !== "anthropic_compatible") {
        throw new TypeError("settings.putModelRoute local.protocol is malformed");
    }
    const baseURL = input.local.base_url;
    if (typeof baseURL !== "string" ||
        baseURL === "" ||
        baseURL.trim() !== baseURL ||
        new TextEncoder().encode(baseURL).byteLength > 512) {
        throw new TypeError("settings.putModelRoute local.base_url is malformed");
    }
    try {
        const parsed = new URL(baseURL);
        if (parsed.protocol !== "https:" && parsed.protocol !== "http:") {
            throw new TypeError("settings.putModelRoute local.base_url scheme invalid");
        }
        if (parsed.username || parsed.password || parsed.hash) {
            throw new TypeError("settings.putModelRoute local.base_url must not include credentials or fragment");
        }
        if (parsed.protocol === "http:") {
            const host = parsed.hostname.toLowerCase();
            if (host !== "127.0.0.1" && host !== "localhost" && host !== "::1") {
                throw new TypeError("settings.putModelRoute http base_url is only allowed for loopback");
            }
        }
    }
    catch (error) {
        if (error instanceof TypeError) {
            throw error;
        }
        throw new TypeError("settings.putModelRoute local.base_url is not a URL");
    }
    const modelID = input.local.model_id;
    if (typeof modelID !== "string" ||
        modelID === "" ||
        modelID.trim() !== modelID ||
        modelID.length > 128 ||
        !/^[A-Za-z0-9._\-:/]+$/u.test(modelID)) {
        throw new TypeError("settings.putModelRoute local.model_id is malformed");
    }
    const localBody = {
        protocol,
        base_url: baseURL,
        model_id: modelID,
    };
    if (input.local.clear_api_key === true) {
        localBody.clear_api_key = true;
    }
    else if (input.local.clear_api_key !== undefined) {
        throw new TypeError("settings.putModelRoute local.clear_api_key must be true when set");
    }
    if (input.local.api_key !== undefined) {
        if (typeof input.local.api_key !== "string") {
            throw new TypeError("settings.putModelRoute local.api_key must be a string");
        }
        if (input.local.api_key === "") {
            throw new TypeError("settings.putModelRoute local.api_key must not be empty when provided");
        }
        if (new TextEncoder().encode(input.local.api_key).byteLength > 4096 ||
            /[\u0000-\u001f\u007f]/u.test(input.local.api_key)) {
            throw new TypeError("settings.putModelRoute local.api_key is malformed");
        }
        localBody.api_key = input.local.api_key;
    }
    body.local = localBody;
    return body;
}
function validateModelRouteSettingsResult(result) {
    if (!result.ok) {
        return result;
    }
    const data = result.data;
    if (data === null || typeof data !== "object" || Array.isArray(data)) {
        throw new TypeError("settings model-route response is malformed");
    }
    const record = data;
    if (Object.prototype.hasOwnProperty.call(record, "api_key")) {
        throw new TypeError("settings model-route response must not include api_key");
    }
    assertExactKeys(record, ["preferred_route", "local", "updated_at"], "settings model-route response");
    const route = record.preferred_route;
    if (route !== "local" && route !== "official") {
        throw new TypeError("settings model-route preferred_route is malformed");
    }
    if (typeof record.updated_at !== "string" ||
        record.updated_at === "" ||
        Number.isNaN(Date.parse(record.updated_at))) {
        throw new TypeError("settings model-route updated_at is malformed");
    }
    const local = record.local;
    if (local === null || typeof local !== "object" || Array.isArray(local)) {
        throw new TypeError("settings model-route local is malformed");
    }
    const localRecord = local;
    if (Object.prototype.hasOwnProperty.call(localRecord, "api_key")) {
        throw new TypeError("settings model-route local must not include api_key");
    }
    assertExactKeys(localRecord, ["protocol", "base_url", "model_id", "api_key_configured"], "settings model-route local");
    for (const key of ["protocol", "base_url", "model_id"]) {
        if (typeof localRecord[key] !== "string") {
            throw new TypeError(`settings model-route local.${key} is malformed`);
        }
    }
    if (typeof localRecord.api_key_configured !== "boolean") {
        throw new TypeError("settings model-route local.api_key_configured is malformed");
    }
    return {
        ...result,
        data: {
            preferred_route: route,
            local: {
                protocol: localRecord.protocol,
                base_url: localRecord.base_url,
                model_id: localRecord.model_id,
                api_key_configured: localRecord.api_key_configured,
            },
            updated_at: record.updated_at,
        },
    };
}
function buildAgentCreateThreadRequest(input) {
    assertPlainObject(input, "agent.createThread input");
    assertExactKeys(input, ["threadUUID", "name", "agentMode"], "agent.createThread input");
    const threadUUID = validateCanonicalV4ThreadUUID(input.threadUUID);
    const name = validateAgentThreadName(input.name);
    const agentMode = validateAgentMode(input.agentMode, "agent.createThread agentMode", 64);
    return {
        threadUUID,
        body: { name, agent_mode: agentMode },
    };
}
function validateAgentCreateThreadResult(result, request) {
    if (!result.ok) {
        return result;
    }
    try {
        return {
            ...result,
            data: parseAgentCreateThreadData(result.data, result.status, request),
        };
    }
    catch {
        throw new TypeError("agent.createThread response is malformed");
    }
}
function parseAgentCreateThreadData(value, status, request) {
    assertPlainObject(value, "agent.createThread response");
    if (status === 202) {
        assertExactKeys(value, ["state", "thread_uuid"], "agent.createThread pending response");
        if (value.state !== "pending_local_sync" ||
            validateCanonicalV4ThreadUUID(value.thread_uuid) !== request.threadUUID) {
            throw new TypeError("agent.createThread pending response is invalid");
        }
        return {
            state: "pending_local_sync",
            thread_uuid: request.threadUUID,
        };
    }
    if (status !== 200 && status !== 201) {
        throw new TypeError("agent.createThread ready response status is invalid");
    }
    assertExactKeys(value, ["state", "created", "thread"], "agent.createThread ready response");
    if (value.state !== "ready" ||
        typeof value.created !== "boolean" ||
        status !== (value.created ? 201 : 200)) {
        throw new TypeError("agent.createThread ready response is invalid");
    }
    assertPlainObject(value.thread, "agent.createThread response thread");
    assertExactKeys(value.thread, [
        "uuid",
        "name",
        "agent_mode",
        "message_count",
        "updated_at",
        "cloud_sync_state",
    ], "agent.createThread response thread");
    const uuid = validateCanonicalV4ThreadUUID(value.thread.uuid);
    const name = validateAgentThreadName(value.thread.name);
    const agentMode = validateAgentMode(value.thread.agent_mode, "agent.createThread response agent_mode", 64);
    if (uuid !== request.threadUUID ||
        (value.created && name !== request.body.name) ||
        (value.created && agentMode !== request.body.agent_mode) ||
        !Number.isSafeInteger(value.thread.message_count) ||
        value.thread.message_count < 0 ||
        typeof value.thread.updated_at !== "string" ||
        value.thread.updated_at.trim() === "" ||
        !Number.isFinite(Date.parse(value.thread.updated_at)) ||
        (value.thread.cloud_sync_state !== "synced" &&
            value.thread.cloud_sync_state !== "paused")) {
        throw new TypeError("agent.createThread response thread is invalid");
    }
    return {
        state: "ready",
        created: value.created,
        thread: {
            uuid,
            name,
            agent_mode: agentMode,
            message_count: value.thread.message_count,
            updated_at: value.thread.updated_at,
            cloud_sync_state: value.thread.cloud_sync_state,
        },
    };
}
function validateAgentRecoverableTurnListResult(result) {
    if (!result.ok) {
        return result;
    }
    try {
        if (result.status !== 200) {
            throw new TypeError("unexpected status");
        }
        assertPlainObject(result.data, "agent.listRecoverableTurns response");
        assertExactKeys(result.data, ["items", "count"], "agent.listRecoverableTurns response");
        if (!Array.isArray(result.data.items) ||
            !Number.isSafeInteger(result.data.count) ||
            result.data.count !== result.data.items.length) {
            throw new TypeError("invalid recoverable turn list");
        }
        const seenTurnUUIDs = new Set();
        const items = result.data.items.map((item) => {
            assertPlainObject(item, "agent.listRecoverableTurns item");
            assertExactKeys(item, [
                "turn_uuid",
                "thread_uuid",
                "user_text",
                "chat_mode",
                "state",
                "last_error_kind",
                "updated_at",
            ], "agent.listRecoverableTurns item");
            const turnUUID = validateCanonicalV4UUID(item.turn_uuid, "agent.listRecoverableTurns turn_uuid");
            const threadUUID = validateThreadUUID(item.thread_uuid);
            const userText = validateAgentUserText(item.user_text);
            const chatMode = validateAgentMode(item.chat_mode, "agent.listRecoverableTurns chat_mode", 100);
            if (item.state !== "interrupted" ||
                typeof item.last_error_kind !== "string" ||
                !hasWellFormedUTF16(item.last_error_kind) ||
                /[\u0000-\u001f\u007f]/u.test(item.last_error_kind) ||
                new TextEncoder().encode(item.last_error_kind).byteLength > 128 ||
                typeof item.updated_at !== "string" ||
                item.updated_at.trim() === "" ||
                !Number.isFinite(Date.parse(item.updated_at)) ||
                seenTurnUUIDs.has(turnUUID)) {
                throw new TypeError("invalid recoverable turn item");
            }
            seenTurnUUIDs.add(turnUUID);
            return {
                turn_uuid: turnUUID,
                thread_uuid: threadUUID,
                user_text: userText,
                chat_mode: chatMode,
                state: "interrupted",
                last_error_kind: item.last_error_kind,
                updated_at: item.updated_at,
            };
        });
        return {
            ...result,
            data: { items, count: items.length },
        };
    }
    catch {
        throw new TypeError("agent.listRecoverableTurns response is malformed");
    }
}
function validateCanonicalV4UUID(value, label) {
    if (typeof value !== "string" ||
        !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(value)) {
        throw new TypeError(`${label} must be a canonical v4 UUID`);
    }
    return value;
}
function validateCanonicalV4ThreadUUID(value) {
    return validateCanonicalV4UUID(value, "agent.createThread threadUUID");
}
function validateAgentThreadName(value) {
    if (typeof value !== "string" ||
        value === "" ||
        value.trim() !== value ||
        !hasWellFormedUTF16(value) ||
        /[\u0000-\u001f\u007f]/u.test(value)) {
        throw new TypeError("agent.createThread name is malformed");
    }
    if (new TextEncoder().encode(value).byteLength > 200) {
        throw new RangeError("agent.createThread name exceeds 200 bytes");
    }
    return value;
}
function buildAgentSidecarTurnRequest(input, callback) {
    assertPlainObject(input, "agent.startTurn input");
    assertAllowedKeys(input, ["threadUUID", "userText", "chatMode", "fileIDs"], "agent.startTurn input");
    if (typeof callback !== "function") {
        throw new TypeError("agent.startTurn callback must be a function");
    }
    const threadUUID = validateThreadUUID(input.threadUUID);
    const userText = validateAgentUserText(input.userText);
    const chatMode = validateAgentChatMode(input.chatMode);
    const fileIDs = validateAgentTurnFileIDs(input.fileIDs);
    const payload = { stream: true };
    if (fileIDs.length > 0) {
        payload.files = fileIDs;
    }
    return {
        thread_uuid: threadUUID,
        user_text: userText,
        chat_mode: chatMode,
        payload,
    };
}
// validateAgentTurnFileIDs normalizes the optional fileIDs input on
// agent.startTurn: undefined → empty, otherwise a deduped array of positive
// safe integers with a small cap (aligned with the sidecar payload limit).
function validateAgentTurnFileIDs(value) {
    if (value === undefined) {
        return [];
    }
    if (!Array.isArray(value)) {
        throw new TypeError("agent.startTurn fileIDs must be an array");
    }
    if (value.length > 10) {
        throw new RangeError("agent.startTurn fileIDs exceeds 10 entries");
    }
    const seen = new Set();
    const out = [];
    for (const id of value) {
        if (typeof id !== "number" || !Number.isSafeInteger(id) || id <= 0) {
            throw new TypeError("agent.startTurn fileIDs must be positive integers");
        }
        if (seen.has(id)) {
            throw new TypeError("agent.startTurn fileIDs must be unique");
        }
        seen.add(id);
        out.push(id);
    }
    return out;
}
function validateAgentUserText(value) {
    if (typeof value !== "string" || value.trim() === "") {
        throw new TypeError("agent.startTurn userText must be a non-empty string");
    }
    if (!hasWellFormedUTF16(value)) {
        throw new TypeError("agent.startTurn userText contains malformed UTF-16");
    }
    if (/\u0000/u.test(value)) {
        throw new TypeError("agent.startTurn userText contains a null character");
    }
    const maxBytes = 256 * 1024;
    if (new TextEncoder().encode(value).byteLength > maxBytes) {
        throw new RangeError(`agent.startTurn userText exceeds ${maxBytes} bytes`);
    }
    return value;
}
function validateAgentChatMode(value) {
    return validateAgentMode(value, "agent.startTurn chatMode", 100);
}
function validateAgentMode(value, label, maxLength) {
    if (typeof value !== "string" ||
        value === "" ||
        value.trim() !== value ||
        value.length > maxLength ||
        !/^[A-Za-z][A-Za-z0-9_-]*$/u.test(value)) {
        throw new TypeError(`${label} is malformed`);
    }
    return value;
}
function hasWellFormedUTF16(value) {
    for (let index = 0; index < value.length; index += 1) {
        const code = value.charCodeAt(index);
        if (code >= 0xd800 && code <= 0xdbff) {
            const next = value.charCodeAt(index + 1);
            if (!Number.isInteger(next) || next < 0xdc00 || next > 0xdfff) {
                return false;
            }
            index += 1;
            continue;
        }
        if (code >= 0xdc00 && code <= 0xdfff) {
            return false;
        }
    }
    return true;
}
function validateTurnID(value) {
    return validateCanonicalV4UUID(value, "agent.cancelTurn turnID");
}
async function execute(deps, route, pathOverride, jsonBody) {
    const headers = new Headers({ Accept: "application/json" });
    const init = {
        method: route.method,
        headers,
    };
    if (route.body === "json") {
        const body = JSON.stringify(jsonBody);
        const limit = JSON_BODY_LIMITS[route.bridgeMethod];
        if (limit !== undefined && new TextEncoder().encode(body).byteLength > limit) {
            throw new RangeError(`${route.bridgeMethod} request body exceeds ${limit} bytes`);
        }
        headers.set("Content-Type", route.contentType);
        init.body = body;
    }
    else if (jsonBody !== undefined) {
        throw new TypeError(`${route.bridgeMethod} does not accept a request body`);
    }
    const response = await deps.request(pathOverride ?? route.path, init);
    const rawBody = await response.text();
    const payload = rawBody === "" ? null : JSON.parse(rawBody);
    const metadata = {
        status: response.status,
        statusText: response.statusText,
        headers: { ...response.headers },
    };
    if (response.ok) {
        return { ok: true, ...metadata, data: payload };
    }
    return { ok: false, ...metadata, error: payload };
}
// executeMultipart sends a multipart/form-data body (file uploads). Unlike
// execute, it does NOT set Content-Type — fetch derives the boundary from the
// FormData, and setting it manually would corrupt the sidecar's parse.
async function executeMultipart(deps, route, path, formData) {
    const init = {
        method: route.method,
        headers: new Headers({ Accept: "application/json" }),
        body: formData,
    };
    const response = await deps.request(path, init);
    const rawBody = await response.text();
    const payload = rawBody === "" ? null : JSON.parse(rawBody);
    const metadata = {
        status: response.status,
        statusText: response.statusText,
        headers: { ...response.headers },
    };
    if (response.ok) {
        return { ok: true, ...metadata, data: payload };
    }
    return { ok: false, ...metadata, error: payload };
}
// validateAgentThreadFileUploadResult narrows an upload response into the typed
// result, or re-throws as a malformed-response TypeError (matching the
// createThread validator's strictness).
function validateAgentThreadFileUploadResult(result) {
    if (!result.ok) {
        return result;
    }
    try {
        return {
            ...result,
            data: parseAgentThreadFileUploadData(result.data),
        };
    }
    catch {
        throw new TypeError("agent.uploadThreadFile response is malformed");
    }
}
function parseAgentThreadFileUploadData(value) {
    assertPlainObject(value, "agent.uploadThreadFile response");
    assertExactKeys(value, ["file_id", "file_name", "mime_type", "file_type", "file_size"], "agent.uploadThreadFile response");
    if (typeof value.file_id !== "number" ||
        !Number.isSafeInteger(value.file_id) ||
        value.file_id <= 0) {
        throw new TypeError("agent.uploadThreadFile response file_id is invalid");
    }
    if (typeof value.file_name !== "string" ||
        typeof value.mime_type !== "string" ||
        typeof value.file_type !== "string") {
        throw new TypeError("agent.uploadThreadFile response string fields are invalid");
    }
    if (typeof value.file_size !== "number" ||
        !Number.isSafeInteger(value.file_size) ||
        value.file_size < 0) {
        throw new TypeError("agent.uploadThreadFile response file_size is invalid");
    }
    return value;
}
function buildListThreadsPath(options) {
    if (options !== undefined) {
        assertPlainObject(options, "history.listThreads options");
        assertAllowedKeys(options, ["limit", "includePaused"], "history.listThreads options");
    }
    const params = new URLSearchParams();
    if (options?.limit !== undefined) {
        params.set("limit", String(validateLimit(options.limit, 500, "history.listThreads limit")));
    }
    if (options?.includePaused !== undefined) {
        if (typeof options.includePaused !== "boolean") {
            throw new TypeError("history.listThreads includePaused must be boolean");
        }
        params.set("include_paused", String(options.includePaused));
    }
    return appendQuery(ROUTES.historyListThreads.path, params);
}
function buildListMessagesPath(options) {
    assertPlainObject(options, "history.listMessages options");
    assertAllowedKeys(options, ["threadUUID", "limit"], "history.listMessages options");
    const threadUUID = validateThreadUUID(options.threadUUID);
    const params = new URLSearchParams();
    if (options.limit !== undefined) {
        params.set("limit", String(validateLimit(options.limit, 1000, "history.listMessages limit")));
    }
    return appendQuery(ROUTES.historyListMessages.path.replace(":uuid", encodeURIComponent(threadUUID)), params);
}
function buildTriggerSyncPath(options) {
    if (options !== undefined) {
        assertPlainObject(options, "system.triggerSync options");
        assertAllowedKeys(options, ["threadUUID"], "system.triggerSync options");
    }
    const params = new URLSearchParams();
    if (options?.threadUUID !== undefined) {
        params.set("thread", validateThreadUUID(options.threadUUID));
    }
    return appendQuery(ROUTES.systemTriggerSync.path, params);
}
function appendQuery(path, params) {
    const query = params.toString();
    return query === "" ? path : `${path}?${query}`;
}
function validateLimit(value, max, label) {
    if (!Number.isSafeInteger(value) ||
        value < 1 ||
        value > max) {
        throw new RangeError(`${label} must be an integer between 1 and ${max}`);
    }
    return value;
}
function validateThreadUUID(value) {
    if (typeof value !== "string" || value === "") {
        throw new TypeError("threadUUID must be a non-empty string");
    }
    if (value.trim() !== value ||
        /[\u0000-\u001f\u007f/?#\\]/u.test(value) ||
        new TextEncoder().encode(value).byteLength > 200) {
        throw new TypeError("threadUUID is malformed");
    }
    return value;
}
function validateRendererLogInput(value) {
    assertPlainObject(value, "system.writeLog entry");
    assertAllowedKeys(value, ["level", "message", "context"], "system.writeLog entry");
    if (value.level !== "error" && value.level !== "warn" && value.level !== "info") {
        throw new TypeError("system.writeLog level must be error, warn, or info");
    }
    if (typeof value.message !== "string" || value.message === "") {
        throw new TypeError("system.writeLog message must be a non-empty string");
    }
    if (value.context !== undefined) {
        assertPlainObject(value.context, "system.writeLog context");
    }
}
function assertPlainObject(value, label) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
        throw new TypeError(`${label} must be an object`);
    }
}
function assertAllowedKeys(value, allowed, label) {
    const allowedSet = new Set(allowed);
    for (const key of Object.keys(value)) {
        if (!allowedSet.has(key)) {
            throw new TypeError(`${label} contains unsupported field ${key}`);
        }
    }
}
function assertExactKeys(value, required, label) {
    assertAllowedKeys(value, required, label);
    const actual = Object.keys(value);
    if (actual.length !== required.length ||
        required.some((key) => !Object.prototype.hasOwnProperty.call(value, key))) {
        throw new TypeError(`${label} must contain exactly ${required.join(", ")}`);
    }
}
  window.__workmaxDesktopBridge = { createDesktopBridge, DESKTOP_BRIDGE_VERSION };
})();
