package globals

var CountryMap = map[string]string{
	"美国":         "United States of America",
	"中国":         "China",
	"加拿大":        "Canada",
	"英国":         "United Kingdom",
	"澳大利亚":       "Australia",
	"新西兰":        "New Zealand",
	"日本":         "Japan",
	"韩国":         "South Korea",
	"新加坡":        "Singapore",
	"马来西亚":       "Malaysia",
	"泰国":         "Thailand",
	"印度":         "India",
	"印度尼西亚":      "Indonesia",
	"菲律宾":        "Philippines",
	"越南":         "Vietnam",
	"柬埔寨":        "Cambodia",
	"缅甸":         "Myanmar",
	"老挝":         "Laos",
	"文莱":         "Brunei",
	"阿富汗":        "Afghanistan",
	"阿联酋":        "United Arab Emirates",
	"阿曼":         "Oman",
	"阿塞拜疆":       "Azerbaijan",
	"巴基斯坦":       "Pakistan",
	"孟加拉":        "Bangladesh",
	"巴勒斯坦":       "Palestine",
	"巴林":         "Bahrain",
	"巴拿马":        "Panama",
	"巴布亚新几内亚":    "Papua New Guinea",
	"莫桑比克":       "Mozambique",
	"安哥拉":        "Angola",
	"尼泊尔":        "Nepal",
	"海地":         "Haiti",
	"危地马拉":       "Guatemala",
	"洪都拉斯":       "Honduras",
	"萨尔瓦多":       "El Salvador",
	"尼加拉瓜":       "Nicaragua",
	"巴巴多斯":       "Barbados",
	"不丹":         "Bhutan",
	"马尔代夫":       "Maldives",
	"吉尔吉斯斯坦":     "Kyrgyzstan",
	"哈萨克斯坦":      "Kazakhstan",
	"塔吉克斯坦":      "Tajikistan",
	"土库曼斯坦":      "Turkmenistan",
	"白俄罗斯":       "Belarus",
	"百慕大":        "Bermuda",
	"保加利亚":       "Bulgaria",
	"北马里亚纳群岛":    "Northern Mariana Islands",
	"北塞浦路斯":      "Northern Cyprus",
	"北爱尔兰":       "Northern Ireland",
	"北马其顿":       "North Macedonia",
	"博茨瓦纳":       "Botswana",
	"博内尔岛":       "Bonaire",
	"波多黎各":       "Puerto Rico",
	"波斯尼亚和黑塞哥维那": "Bosnia and Herzegovina",
	"马拉维":        "Malawi",
	"奥地利":        "Austria",
	"希腊":         "Greece",
	"巴西":         "Brazil",
	"智利":         "Chile",
	"尼日利亚":       "Nigeria",
	"塞尔维亚":       "Serbia",
	"阿尔巴尼亚":      "Albania",
	"瑞士":         "Switzerland",
	"瑞典":         "Sweden",
	"斯洛伐克":       "Slovakia",
	"斯洛文尼亚":      "Slovenia",
	"乌兹别克斯坦":     "Uzbekistan",
	"法国":         "France",
	"德国":         "Germany",
	"荷兰":         "Netherlands",
	"比利时":        "Belgium",
	"意大利":        "Italy",
	"西班牙":        "Spain",
	"葡萄牙":        "Portugal",
	"芬兰":         "Finland",
	"挪威":         "Norway",
	"丹麦":         "Denmark",
	"冰岛":         "Iceland",
	"爱尔兰":        "Ireland",
	"波兰":         "Poland",
	"捷克":         "Czechia",
	"匈牙利":        "Hungary",
	"罗马尼亚":       "Romania",
	"克罗地亚":       "Croatia",
	"土耳其":        "Turkey",
	"乌克兰":        "Ukraine",
	"乌拉圭":        "Uruguay",
	"委内瑞拉":       "Venezuela",
	"赞比亚":        "Zambia",
	"津巴布韦":       "Zimbabwe",
	"也门":         "Yemen",
	"哥伦比亚":       "Colombia",
	"纳米比亚":       "Namibia",
	"墨西哥":        "Mexico",
	"古巴":         "Cuba",
	"厄瓜多尔":       "Ecuador",
	"秘鲁":         "Peru",
	"玻利维亚":       "Bolivia",
	"哥斯达黎加":      "Costa Rica",
	"多米尼加":       "Dominican Republic",
	"多米尼克":       "Dominica",
	"多米尼加共和国":    "Dominican Republic",
	"多米尼加联邦":     "Dominican Republic",
	"多米尼加国":      "Dominican Republic",
	"多米尼加合众国":    "Dominican Republic",
	"多米尼加自由国":    "Dominican Republic",
	"多米尼加联邦共和国":  "Dominican Republic",
	"伊拉克":        "Iraq",
	"埃及":         "Egypt",
	"伊朗":         "Iran",
	"以色列":        "Israel",
	"约旦":         "Jordan",
	"黎巴嫩":        "Lebanon",
	"沙特阿拉伯":      "Saudi Arabia",
	"叙利亚":        "Syria",
	"阿尔及利亚":      "Algeria",
	"摩洛哥":        "Morocco",
	"突尼斯":        "Tunisia",
	"肯尼亚":        "Kenya",
	"埃塞俄比亚":      "Ethiopia",
	"加纳":         "Ghana",
	"毛里塔尼亚":      "Mauritania",
	"尼日尔":        "Niger",
	"圣多美和普林西比":   "Sao Tome and Principe",
	"索马里":        "Somalia",
	"苏里南":        "Suriname",
	"多哥":         "Togo",
	"东帝汶":        "Timor-Leste",
	"乌干达":        "Uganda",
	"卢旺达":        "Rwanda",
	"马达加斯加":      "Madagascar",
	"塞内加尔":       "Senegal",
	"塞拉利昂":       "Sierra Leone",
	"贝宁":         "Benin",
	"布基纳法索":      "Burkina Faso",
	"布隆迪":        "Burundi",
	"佛得角":        "Cabo Verde",
	"中非共和国":      "Central African Republic",
	"乍得":         "Chad",
	"科摩罗":        "Comoros",
	"吉布提":        "Djibouti",
	"赤道几内亚":      "Equatorial Guinea",
	"厄立特里亚":      "Eritrea",
	"冈比亚":        "Gambia",
	"几内亚":        "Guinea",
	"几内亚比绍":      "Guinea-Bissau",
	"莱索托":        "Lesotho",
	"利比里亚":       "Liberia",
	"利比亚":        "Libya",
	"南非":         "South Africa",
	"斯威士兰":       "Eswatini",
	"阿根廷":        "Argentina",
	"俄罗斯":        "Russia",
	"蒙古":         "Mongolia",
	"卡塔尔":        "Qatar",
	"非洲地区":       "Africa",
	"香港":         "Hong Kong",
	"澳门":         "Macau",
	// 历史名“马其顿”统一映射为现用国名“North Macedonia”
	"马其顿":     "North Macedonia",
	"马里":      "Mali",
	"牙买加":     "Jamaica",
	"喀麦隆":     "Cameroon",
	"拉脱维亚":    "Latvia",
	"苏丹":      "Sudan",
	"圭亚那":     "Guyana",
	"斯里兰卡":    "Sri Lanka",
	"塞浦路斯":    "Cyprus",
	"南苏丹":     "South Sudan",
	"科特迪瓦":    "Cote d'Ivoire",
	"刚果民主共和国": "Democratic Republic of the Congo",
	"刚果（金）":   "Democratic Republic of the Congo",
	"刚果共和国":   "Republic of the Congo",
	"刚果（布）":   "Republic of the Congo",
	"爱沙尼亚":    "Estonia",
	"立陶宛":     "Lithuania",
	"格鲁吉亚":    "Georgia",
	"亚美尼亚":    "Armenia",
	"卢森堡":     "Luxembourg",
	"马耳他":     "Malta",
	"安道尔":     "Andorra",
	"列支敦士登":   "Liechtenstein",
	"摩纳哥":     "Monaco",
	"圣马力诺":    "San Marino",
	"梵蒂冈":     "Vatican City",
	"塞舌尔":     "Seychelles",
	"毛里求斯":    "Mauritius",
	"坦桑尼亚":    "Tanzania",
	"摩尔多瓦":    "Moldova",
	"黑山":      "Montenegro",
	"斐济":      "Fiji",
	"基里巴斯":    "Kiribati",
	"马绍尔群岛":   "Marshall Islands",
	"密克罗尼西亚":  "Micronesia",
	"瑙鲁":      "Nauru",
	"帕劳":      "Palau",
	"萨摩亚":     "Samoa",
	"所罗门群岛":   "Solomon Islands",
	"汤加":      "Tonga",
	"图瓦卢":     "Tuvalu",
	"瓦努阿图":    "Vanuatu",
	"科索沃":     "Kosovo",
}
