#!/usr/bin/env bash
# Regenerates the renderer's browser build of the typed desktop bridge.
#
# desktop-bridge.ts is the single source of the typed facade contract. The
# renderer consumes a GENERATED ES-module build of it rather than a hand-copied
# port, so the two shells cannot drift while both exist — and so the contract
# checker keeps comparing against one definition.
#
# Output: desktop/renderer/en/desktop/lib/desktop-bridge.js (checked in, so a
# renderer-only change needs no TypeScript toolchain).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$REPO_ROOT/desktop/renderer/src/desktop-bridge.ts"
OUT_DIR="$REPO_ROOT/desktop/renderer/en/desktop/lib"
STAGING="$(mktemp -d "${TMPDIR:-/tmp}/workmax-renderer-lib.XXXXXX")"
trap 'rm -rf "$STAGING"' EXIT

if [ ! -f "$SRC" ]; then
  echo "==> error: $SRC not found." >&2
  exit 1
fi

# TypeScript is a build-time-only dependency of the renderer: the generated
# output is checked in, so a renderer-only change needs no toolchain at all.
cd "$REPO_ROOT/desktop/renderer"
[ -d node_modules ] || npm install
npx --no-install tsc "$SRC" \
  --target ES2022 --module ES2022 --moduleResolution bundler --strict \
  --outDir "$STAGING"

# Emit a classic script, not an ES module. The renderer loads its scripts
# classically and in order; making this one a module would defer it past
# renderer.js, which expects the bridge to already be installed on window.
#
# The transform is two known lines, asserted rather than assumed: if the
# source grows another export, this fails loudly instead of silently shipping
# a half-converted file.
exports_found="$(grep -c '^export ' "$STAGING/desktop-bridge.js")"
if [ "$exports_found" != "2" ]; then
  echo "==> error: expected exactly 2 top-level exports, found $exports_found." >&2
  echo "    Update this script's transform to match desktop-bridge.ts." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"
{
  echo "// GENERATED by desktop/scripts/build-renderer-lib.sh — do not edit."
  echo "// Source: desktop/renderer/src/desktop-bridge.ts"
  echo "(function () {"
  sed -e 's/^export const DESKTOP_BRIDGE_VERSION/const DESKTOP_BRIDGE_VERSION/' \
      -e 's/^export function createDesktopBridge/function createDesktopBridge/' \
      "$STAGING/desktop-bridge.js"
  echo "  window.__workmaxDesktopBridge = { createDesktopBridge, DESKTOP_BRIDGE_VERSION };"
  echo "})();"
} > "$OUT_DIR/desktop-bridge.js"
echo "ok wrote $OUT_DIR/desktop-bridge.js"
