package skills

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// Field length caps. Enforced at parse time so a runaway manifest
// (auto-generated by a future tool, copy-paste typo, hostile overlay)
// can't smuggle a multi-MB blob through the loader cache. Numbers are
// generous compared to anything our 25 official skills use today;
// raise them when a real skill needs more.
const (
	maxNameLen        = 64 // skill name + script name + reference basename
	maxVersionLen     = 32
	maxDescriptionLen = 512
	maxScriptPathLen  = 256
	maxLegacyRefLen   = 128
	maxKindLen        = 64
	maxArtifactLen    = 64
)

// Manifest is the parsed shape of a skill's skill.yaml. Fields are
// kept conservative — anything that doesn't actively drive the
// loader stays out so future changes don't carry dead schema.
//
// `Legacy` is the migration shim: a skill without its own SKILL.md
// can declare which legacy identity_X.md / output_format_X.md it
// inherits from, and the loader will synthesize a bundle from those
// files. Fully-migrated skills omit the Legacy block.
type Manifest struct {
	Name        string `yaml:"name"`
	Version     string `yaml:"version"`
	Description string `yaml:"description"`

	// Triggers tell the runtime when this skill should be selected.
	// Today the only trigger is `agent_mode` — keyword-based fuzzy
	// triggering is left as a future extension once the registry
	// has more than one selection axis.
	Triggers struct {
		AgentMode string `yaml:"agent_mode"`
	} `yaml:"triggers"`

	// Required inputs the skill expects before it should generate
	// anything. The runtime can use these to short-circuit a turn
	// with a clarifying question instead of letting the model
	// hallucinate substitutes.
	RequiredInputs []InputRequirement `yaml:"required_inputs"`

	// References declares which markdown bodies get inlined into
	// the SKILL.md at bundle time. `shared` resolves under
	// skills/_shared/<name>.md; `local` under
	// skills/<skill>/references/<name>.md.
	References struct {
		Shared []string `yaml:"shared"`
		Local  []string `yaml:"local"`
	} `yaml:"references"`

	// Scripts declares post-generation hooks the runtime should
	// invoke (e.g. Playwright validation of a rendered PPTX). The
	// loader exposes these in SkillBundle.PostScripts; wiring them
	// to the agent_processor OnDone path is a separate change
	// (kept narrow so this PR is reorganization, not new behaviour).
	Scripts []ScriptDescriptor `yaml:"scripts"`

	// Artifacts declares the kind of user-facing outputs this skill
	// is expected to produce. This is P0 for the design-workspace
	// roadmap: downstream catalog, telemetry, preview registries,
	// and critique/redo flows need a machine-readable artifact
	// matrix instead of inferring from prose in SKILL.md.
	Artifacts *ArtifactMetadata `yaml:"artifacts,omitempty"`

	// Legacy migration fields. When set, the loader synthesizes
	// the SKILL.md body from prompts/templates/identity_<X>.md +
	// output_format_<X>.md instead of reading SKILL.md from the
	// skill directory. This lets a skill ship its skill.yaml
	// before the SKILL.md is hand-rewritten, keeping behaviour
	// byte-identical to the legacy path. Fully-migrated skills
	// drop the Legacy block.
	Legacy *LegacyInherits `yaml:"legacy,omitempty"`

	// QuestionForm declares the M1 turn-1 discovery form schema for
	// this skill. When Enabled, the runtime intercepts the first
	// turn of a fresh thread and emits a question_form block + done
	// event INSTEAD of calling the SDK.
	//
	// Empty / unset = no short-circuit (default). Sprint A wires
	// this for ppt / character / productShot / marketingPoster /
	// flashCard via PR-6.
	QuestionForm *QuestionForm `yaml:"question_form,omitempty"`

	// DirectionsFallback declares whether this skill should fall
	// back to the M2 visual directions picker when:
	//   - the question_form has been answered (or skipped) AND
	//   - no <brand-spec> is in scope (user has no active brand
	//     asset; thread workdir doesn't carry brand-spec.md) AND
	//   - no direction has been picked yet for this thread
	//
	// Empty / unset = no fallback (default). Sprint-B M2 enables
	// this on the 5 high-frequency Sprint A skills via skill.yaml.
	// See visual-directions.yaml for the available direction set.
	DirectionsFallback *DirectionsFallback `yaml:"directions_fallback,omitempty"`
}

// DirectionsFallback is the M2 picker config. Mirrors the
// QuestionForm shape — Enabled gates the dispatch, Trigger lets a
// future iteration carve specific failure modes (always vs. only-
// when-no-discovery vs. only-on-explicit-keyword) without breaking
// callers that already wired Enabled=true.
type DirectionsFallback struct {
	Enabled bool `yaml:"enabled"`
	// Trigger is the rule that determines when the picker fires.
	// Default ("no_brand_no_direction_selected") covers Sprint-B.
	// Future variants: "always", "first_turn_only", etc.
	Trigger string `yaml:"trigger,omitempty"`
	// SkipKey is the locale key for the "let agent decide" button
	// label. Defaults to "form.skip" when empty.
	SkipKey string `yaml:"skip_label_key,omitempty"`
	// PickerSource selects which yaml source to read. Today only
	// "fallback_5" (the visual-directions.yaml default rotation)
	// is supported. Reserved for future per-skill custom rotations.
	PickerSource string `yaml:"picker_source,omitempty"`
}

// QuestionForm is the M1 turn-1 discovery form schema. Field labels
// carry i18n keys that the runtime resolves
// against the user's locale before SSE emit (see
// server/service/tools/workagent/i18n/resolver.go) — at parse time
// we just store the raw keys.
type QuestionForm struct {
	Enabled   bool                   `yaml:"enabled"`
	Trigger   string                 `yaml:"trigger,omitempty"` // "first_turn_no_form_answered" (default) | future variants
	Questions []QuestionFormField    `yaml:"questions"`
	SkipKey   string                 `yaml:"skip_label_key,omitempty"`
	Extra     map[string]interface{} `yaml:",inline"` // future-proofing for fields the schema doesn't yet name
}

// QuestionFormField mirrors the schema in §3.4 — a single radio /
// select / text question. The runtime composes the SSE block from
// these by resolving each LabelKey against the active locale.
type QuestionFormField struct {
	ID       string               `yaml:"id"`
	LabelKey string               `yaml:"label_key"`
	Type     string               `yaml:"type"` // "single_select" | "multi_select" | "text" | "button"
	Required bool                 `yaml:"required,omitempty"`
	Default  string               `yaml:"default,omitempty"`
	Options  []QuestionFormOption `yaml:"options,omitempty"`
}

// QuestionFormOption is one radio choice. LabelKey resolves to a
// translated label; Value is the stable string returned to the
// runtime when the user picks this option.
type QuestionFormOption struct {
	Value    string `yaml:"value"`
	LabelKey string `yaml:"label_key"`
}

// InputRequirement describes a single piece of context the skill
// needs before it can produce useful output. `Kind` is the semantic
// label (brand_assets / topic / page_count / ...). `When` is an
// optional gate: empty = always required; "brand_specified" =
// only required when the user mentioned a specific brand.
type InputRequirement struct {
	Kind string `yaml:"kind" json:"kind"`
	When string `yaml:"when,omitempty" json:"when,omitempty"`
}

// ScriptDescriptor is a post-generation hook. Path is relative to
// the skill directory; When tells the runtime when to invoke it.
type ScriptDescriptor struct {
	Name string `yaml:"name"`
	Path string `yaml:"path"`
	When string `yaml:"when"` // post_generation | pre_send | etc.
}

// ArtifactMetadata is the skill-level artifact matrix consumed by
// catalog/telemetry/preview planning. Keep the schema descriptive
// rather than deeply normalized for now; P1's artifact registry can
// map these strings to stronger DB enums once the runtime surface
// exists.
type ArtifactMetadata struct {
	PrimaryType     string   `yaml:"primary_type" json:"primaryType"`
	OutputTypes     []string `yaml:"output_types" json:"outputTypes"`
	PreviewTypes    []string `yaml:"preview_types" json:"previewTypes"`
	ExportTargets   []string `yaml:"export_targets" json:"exportTargets"`
	CritiqueAnchors []string `yaml:"critique_anchors" json:"critiqueAnchors"`
}

// LegacyInherits is the migration bridge. See Manifest.Legacy.
type LegacyInherits struct {
	InheritsIdentity string `yaml:"inherits_identity"` // e.g. "identity_ppt"
	InheritsOutput   string `yaml:"inherits_output"`   // e.g. "output_format_ppt"
}

// parseManifest decodes raw skill.yaml bytes and validates the result.
// Validation rejects malformed manifests at parse time so the loader
// cache never holds a half-broken Manifest that then fails at every
// Build call with a confusing fs error.
//
// Two kinds of checks:
//   - shape: required fields, length caps (defence against a runaway
//     skill.yaml or a hostile manifest sneaking through a future
//     overlay path)
//   - safety: reference / script paths can't contain '..' / leading
//     '/' / backslashes. embed.FS already rejects these but we want
//     a clear error message at parse time, not "file does not exist"
//     at Build time.
func parseManifest(data []byte) (*Manifest, error) {
	var m Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse skill.yaml: %w", err)
	}
	if err := validateManifest(&m); err != nil {
		return nil, fmt.Errorf("skill.yaml: %w", err)
	}
	return &m, nil
}

func validateManifestForSkillDir(skillDir string, m *Manifest) error {
	if skillDir == "" {
		return fmt.Errorf("skill directory name is required")
	}
	if m == nil {
		return fmt.Errorf("manifest is nil")
	}
	if m.Name != skillDir {
		return fmt.Errorf("name %q must match skill directory %q", m.Name, skillDir)
	}
	if m.Triggers.AgentMode == "" {
		return fmt.Errorf("triggers.agent_mode is required")
	}
	if m.Triggers.AgentMode != skillDir {
		return fmt.Errorf("triggers.agent_mode %q must match skill directory %q", m.Triggers.AgentMode, skillDir)
	}
	return nil
}

func validateManifest(m *Manifest) error {
	if m.Name == "" {
		return fmt.Errorf("name is required")
	}
	if err := validateIdentifier("name", m.Name, maxNameLen); err != nil {
		return err
	}
	if len(m.Version) > maxVersionLen {
		return fmt.Errorf("version exceeds %d bytes", maxVersionLen)
	}
	if len(m.Description) > maxDescriptionLen {
		return fmt.Errorf("description exceeds %d bytes", maxDescriptionLen)
	}

	sharedRefs := map[string]bool{}
	for i, ref := range m.References.Shared {
		if err := validateIdentifier(fmt.Sprintf("references.shared[%d]", i), ref, maxNameLen); err != nil {
			return err
		}
		if sharedRefs[ref] {
			return fmt.Errorf("references.shared[%d] %q is duplicated", i, ref)
		}
		sharedRefs[ref] = true
	}
	localRefs := map[string]bool{}
	for i, ref := range m.References.Local {
		if err := validateIdentifier(fmt.Sprintf("references.local[%d]", i), ref, maxNameLen); err != nil {
			return err
		}
		if localRefs[ref] {
			return fmt.Errorf("references.local[%d] %q is duplicated", i, ref)
		}
		localRefs[ref] = true
	}

	scriptNames := map[string]bool{}
	scriptPaths := map[string]bool{}
	for i, s := range m.Scripts {
		if err := validateIdentifier(fmt.Sprintf("scripts[%d].name", i), s.Name, maxNameLen); err != nil {
			return err
		}
		if scriptNames[s.Name] {
			return fmt.Errorf("scripts[%d].name %q is duplicated", i, s.Name)
		}
		scriptNames[s.Name] = true
		if err := validateRelPath(fmt.Sprintf("scripts[%d].path", i), s.Path, maxScriptPathLen); err != nil {
			return err
		}
		if scriptPaths[s.Path] {
			return fmt.Errorf("scripts[%d].path %q is duplicated", i, s.Path)
		}
		scriptPaths[s.Path] = true
		if !allowedScriptWhen[s.When] {
			return fmt.Errorf("scripts[%d].when %q is not supported", i, s.When)
		}
	}

	requiredInputKeys := map[string]bool{}
	for i, r := range m.RequiredInputs {
		if r.Kind == "" {
			return fmt.Errorf("required_inputs[%d].kind is required", i)
		}
		if len(r.Kind) > maxKindLen {
			return fmt.Errorf("required_inputs[%d].kind exceeds %d bytes", i, maxKindLen)
		}
		if r.When != "" {
			if err := validateIdentifier(fmt.Sprintf("required_inputs[%d].when", i), r.When, maxKindLen); err != nil {
				return err
			}
		}
		key := r.Kind + "\x00" + r.When
		if requiredInputKeys[key] {
			return fmt.Errorf("required_inputs[%d] %q is duplicated", i, r.Kind)
		}
		requiredInputKeys[key] = true
	}

	if err := validateQuestionForm(m.QuestionForm); err != nil {
		return err
	}
	if err := validateDirectionsFallback(m.DirectionsFallback); err != nil {
		return err
	}
	if err := validateArtifacts(m.Artifacts); err != nil {
		return err
	}

	if m.Legacy != nil {
		if err := validateLegacyRef("legacy.inherits_identity", m.Legacy.InheritsIdentity, "identity_"); err != nil {
			return err
		}
		if err := validateLegacyRef("legacy.inherits_output", m.Legacy.InheritsOutput, "output_format_"); err != nil {
			return err
		}
	}

	return nil
}

func validateArtifacts(artifacts *ArtifactMetadata) error {
	if artifacts == nil {
		return nil
	}
	if err := validateIdentifier("artifacts.primary_type", artifacts.PrimaryType, maxArtifactLen); err != nil {
		return err
	}
	if len(artifacts.OutputTypes) == 0 {
		return fmt.Errorf("artifacts.output_types is required")
	}
	if len(artifacts.PreviewTypes) == 0 {
		return fmt.Errorf("artifacts.preview_types is required")
	}
	if len(artifacts.ExportTargets) == 0 {
		return fmt.Errorf("artifacts.export_targets is required")
	}
	if len(artifacts.CritiqueAnchors) == 0 {
		return fmt.Errorf("artifacts.critique_anchors is required")
	}
	outputTypes := map[string]bool{}
	for i, typ := range artifacts.OutputTypes {
		if err := validateIdentifier(fmt.Sprintf("artifacts.output_types[%d]", i), typ, maxArtifactLen); err != nil {
			return err
		}
		if !allowedArtifactOutputTypes[typ] {
			return fmt.Errorf("artifacts.output_types[%d] %q is not supported", i, typ)
		}
		if outputTypes[typ] {
			return fmt.Errorf("artifacts.output_types[%d] %q is duplicated", i, typ)
		}
		outputTypes[typ] = true
	}
	previewTypes := map[string]bool{}
	for i, typ := range artifacts.PreviewTypes {
		if err := validateIdentifier(fmt.Sprintf("artifacts.preview_types[%d]", i), typ, maxArtifactLen); err != nil {
			return err
		}
		if !allowedArtifactPreviewTypes[typ] {
			return fmt.Errorf("artifacts.preview_types[%d] %q is not supported", i, typ)
		}
		if previewTypes[typ] {
			return fmt.Errorf("artifacts.preview_types[%d] %q is duplicated", i, typ)
		}
		if !previewTypeSupportedByOutputs(typ, outputTypes) {
			return fmt.Errorf("artifacts.preview_types[%d] %q is not supported by output_types", i, typ)
		}
		previewTypes[typ] = true
	}
	exportTargets := map[string]bool{}
	for i, target := range artifacts.ExportTargets {
		if err := validateIdentifier(fmt.Sprintf("artifacts.export_targets[%d]", i), target, maxArtifactLen); err != nil {
			return err
		}
		if !allowedArtifactExportTargets[target] {
			return fmt.Errorf("artifacts.export_targets[%d] %q is not supported", i, target)
		}
		if exportTargets[target] {
			return fmt.Errorf("artifacts.export_targets[%d] %q is duplicated", i, target)
		}
		if target != "zip" && !outputTypes[target] {
			return fmt.Errorf("artifacts.export_targets[%d] %q must also be declared in output_types", i, target)
		}
		exportTargets[target] = true
	}
	critiqueAnchors := map[string]bool{}
	for i, anchor := range artifacts.CritiqueAnchors {
		if err := validateIdentifier(fmt.Sprintf("artifacts.critique_anchors[%d]", i), anchor, maxArtifactLen); err != nil {
			return err
		}
		if !allowedCritiqueAnchors[anchor] {
			return fmt.Errorf("artifacts.critique_anchors[%d] %q is not supported", i, anchor)
		}
		if critiqueAnchors[anchor] {
			return fmt.Errorf("artifacts.critique_anchors[%d] %q is duplicated", i, anchor)
		}
		critiqueAnchors[anchor] = true
	}
	return nil
}

func previewTypeSupportedByOutputs(previewType string, outputTypes map[string]bool) bool {
	switch previewType {
	case "deck":
		return outputTypes["pptx"]
	case "html":
		return outputTypes["html"]
	case "image":
		return outputTypes["png"] || outputTypes["jpg"] || outputTypes["svg"] || outputTypes["gif"]
	case "json":
		return outputTypes["json"]
	case "markdown":
		return outputTypes["markdown"]
	case "pdf":
		return outputTypes["pdf"]
	case "video":
		return outputTypes["mp4"]
	default:
		return false
	}
}

var allowedArtifactOutputTypes = map[string]bool{
	"gif":      true,
	"html":     true,
	"jpg":      true,
	"json":     true,
	"markdown": true,
	"mp4":      true,
	"pdf":      true,
	"png":      true,
	"pptx":     true,
	"svg":      true,
}

var allowedArtifactPreviewTypes = map[string]bool{
	"deck":     true,
	"html":     true,
	"image":    true,
	"json":     true,
	"markdown": true,
	"pdf":      true,
	"video":    true,
}

var allowedArtifactExportTargets = map[string]bool{
	"gif":      true,
	"html":     true,
	"jpg":      true,
	"json":     true,
	"markdown": true,
	"mp4":      true,
	"pdf":      true,
	"png":      true,
	"pptx":     true,
	"svg":      true,
	"zip":      true,
}

var allowedCritiqueAnchors = map[string]bool{
	"brand_fit":     true,
	"clarity":       true,
	"compliance":    true,
	"consistency":   true,
	"craft":         true,
	"density":       true,
	"fidelity":      true,
	"functionality": true,
	"goal_fit":      true,
	"hierarchy":     true,
	"originality":   true,
	"pacing":        true,
	"restraint":     true,
}

var allowedScriptWhen = map[string]bool{
	"post_generation": true,
}

func validateQuestionForm(qf *QuestionForm) error {
	if qf == nil || !qf.Enabled {
		return nil
	}
	if len(qf.Questions) == 0 {
		return fmt.Errorf("question_form.questions is required when enabled")
	}
	switch qf.Trigger {
	case "", "first_turn_no_form_answered":
	default:
		return fmt.Errorf("question_form.trigger %q is not supported", qf.Trigger)
	}
	if qf.SkipKey != "" {
		if err := validateI18nKey("question_form.skip_label_key", qf.SkipKey); err != nil {
			return err
		}
	}
	seenQuestionIDs := map[string]bool{}
	for i, q := range qf.Questions {
		if err := validateIdentifier(fmt.Sprintf("question_form.questions[%d].id", i), q.ID, maxKindLen); err != nil {
			return err
		}
		if seenQuestionIDs[q.ID] {
			return fmt.Errorf("question_form.questions[%d].id %q is duplicated", i, q.ID)
		}
		seenQuestionIDs[q.ID] = true
		if err := validateI18nKey(fmt.Sprintf("question_form.questions[%d].label_key", i), q.LabelKey); err != nil {
			return err
		}
		typ := q.Type
		if typ == "" {
			typ = "single_select"
		}
		switch typ {
		case "single_select", "multi_select":
			if len(q.Options) == 0 {
				return fmt.Errorf("question_form.questions[%d].options is required for %s", i, typ)
			}
			seenValues := map[string]bool{}
			for j, opt := range q.Options {
				if err := validateIdentifier(fmt.Sprintf("question_form.questions[%d].options[%d].value", i, j), opt.Value, maxKindLen); err != nil {
					return err
				}
				if err := validateI18nKey(fmt.Sprintf("question_form.questions[%d].options[%d].label_key", i, j), opt.LabelKey); err != nil {
					return err
				}
				if seenValues[opt.Value] {
					return fmt.Errorf("question_form.questions[%d].options[%d].value %q is duplicated", i, j, opt.Value)
				}
				seenValues[opt.Value] = true
			}
			if q.Default != "" && !seenValues[q.Default] {
				return fmt.Errorf("question_form.questions[%d].default %q must match an option value", i, q.Default)
			}
		case "text", "button":
			// No option payload required.
		default:
			return fmt.Errorf("question_form.questions[%d].type %q is not supported", i, q.Type)
		}
	}
	return nil
}

func validateI18nKey(field string, value string) error {
	if value == "" {
		return fmt.Errorf("%s is required", field)
	}
	if len(value) > maxDescriptionLen {
		return fmt.Errorf("%s exceeds %d bytes", field, maxDescriptionLen)
	}
	if strings.ContainsAny(value, "/\\") {
		return fmt.Errorf("%s must not contain path separators", field)
	}
	if strings.Contains(value, "..") {
		return fmt.Errorf("%s must not contain '..'", field)
	}
	if !strings.HasPrefix(value, "form.") {
		return fmt.Errorf("%s %q must start with \"form.\"", field, value)
	}
	return nil
}

func validateDirectionsFallback(df *DirectionsFallback) error {
	if df == nil || !df.Enabled {
		return nil
	}
	switch df.Trigger {
	case "", "no_brand_no_direction_selected":
	default:
		return fmt.Errorf("directions_fallback.trigger %q is not supported", df.Trigger)
	}
	switch df.PickerSource {
	case "", "fallback_5":
	default:
		return fmt.Errorf("directions_fallback.picker_source %q is not supported", df.PickerSource)
	}
	if df.SkipKey != "" {
		if err := validateI18nKey("directions_fallback.skip_label_key", df.SkipKey); err != nil {
			return err
		}
	}
	return nil
}

// validateLegacyRef hardens the Legacy.Inherits* fields. The prefix
// check alone left a defense-in-depth gap — loader.go strips the
// prefix and forwards the remainder to prompts.LoadIdentity /
// LoadOutputFormat as a `mode` name. Without further validation a
// crafted value like `identity_../foo` would slip through and feed
// the downstream lookup a path-traversal segment. Today every
// skill.yaml is embedded at build time so this is dormant; if the
// reverted Phase-5.0 user-overlay subsystem (commit 674a2f9b) ever
// returns, this gate is what stops a hostile overlay from naming
// arbitrary mode lookups. Keep it tight by reusing the same
// no-separators, no-`..`, length-bounded rules the reference and
// script-name validators already enforce.
func validateLegacyRef(field, value, prefix string) error {
	if value == "" {
		return nil // optional — skill can declare just one of the two
	}
	if !strings.HasPrefix(value, prefix) {
		return fmt.Errorf("%s must start with %q", field, prefix)
	}
	if len(value) > maxLegacyRefLen {
		return fmt.Errorf("%s exceeds %d bytes", field, maxLegacyRefLen)
	}
	suffix := strings.TrimPrefix(value, prefix)
	if suffix == "" {
		return fmt.Errorf("%s missing mode name after %q", field, prefix)
	}
	if strings.ContainsAny(suffix, "/\\") {
		return fmt.Errorf("%s must not contain path separators after %q", field, prefix)
	}
	if strings.Contains(suffix, "..") {
		return fmt.Errorf("%s must not contain '..' after %q", field, prefix)
	}
	return nil
}

// validateIdentifier rejects empty / overlong / path-shaped values.
// Reference names and skill names get rendered into embed.FS paths
// (e.g. "_shared/<name>.md") so a name that contains a slash or '..'
// would either escape the skill bundle or feed embed.FS something
// that fails opaquely at read time.
func validateIdentifier(field, value string, maxLen int) error {
	if value == "" {
		return fmt.Errorf("%s is required", field)
	}
	if len(value) > maxLen {
		return fmt.Errorf("%s exceeds %d bytes", field, maxLen)
	}
	if strings.ContainsAny(value, "/\\") {
		return fmt.Errorf("%s must not contain path separators", field)
	}
	if strings.Contains(value, "..") {
		return fmt.Errorf("%s must not contain '..'", field)
	}
	return nil
}

// validateRelPath checks a slash-relative path inside a skill bundle
// (e.g. "scripts/validate-pptx.py"). embed.FS already rejects '..',
// leading '/' and backslashes, but enforcing them here turns runtime
// "file does not exist" errors into clear parse-time messages.
func validateRelPath(field, value string, maxLen int) error {
	if value == "" {
		return fmt.Errorf("%s is required", field)
	}
	if len(value) > maxLen {
		return fmt.Errorf("%s exceeds %d bytes", field, maxLen)
	}
	if strings.HasPrefix(value, "/") {
		return fmt.Errorf("%s must be relative (no leading '/')", field)
	}
	if strings.Contains(value, "\\") {
		return fmt.Errorf("%s must use '/' (not '\\') as separator", field)
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == ".." {
			return fmt.Errorf("%s must not contain '..' segments", field)
		}
	}
	return nil
}
