package constants

const LoraGlobalNegativePrompt = "lowres, blurry, out of focus, jpeg artifacts, bad anatomy, deformed, duplicate subject, extra limbs, extra fingers, text, watermark, logo"

var LoraPrompts = map[string]string{
	"gender-swap":       "single person gender-swapped portrait of the same subject, preserve identity, facial structure, expression, pose, camera angle, lighting and background, realistic skin texture, anatomically correct facial features, high detail, sharp focus, 8k",
	"90s-camera":        "1990s disposable camera portrait, direct flash, film grain, slight color shift, nostalgic mood, candid framing, high detail",
	"youtube-thumbnail": "high-impact youtube thumbnail style portrait, expressive face, dramatic lighting, high contrast, vibrant colors, clear headline safe area, social-media viral aesthetic, sharp focus",
	"pet-meme":          "funny pet meme illustration of the same pet, preserve key fur markings and expression, playful hand-drawn doodle style, exaggerated emotion, clean background, high detail",
	"watermark-remover": "clean image, no watermark, high quality, original content preserved",
	"manga-color":       "manga page colorization, preserve original line art and panel clarity, anime cel shading, vibrant but balanced colors, clean highlights and shadows, high resolution",
	"santa-hat":         "single or group portrait with realistic santa hats, preserve identity, pose, lighting and background, natural hat fabric texture, festive christmas atmosphere, high detail",
	"old-photo":         "old photo restoration and colorization, preserve identity and composition, remove scratches and dust, recover sharp facial details, natural tones, high resolution",
	"beauty-filter":     "single person beauty retouch of the same subject, preserve identity, face shape, expression, lighting and background, natural skin enhancement, refined makeup, realistic texture, studio quality, high detail",
	"ghibsky":           "studio-ghibli-inspired sky illustration, dreamy cloud shapes, pastel palette, soft painterly anime background, whimsical atmosphere, high detail",
	"pixel-art":         "retro pixel art transformation, clean 16-bit look, crisp pixel edges, limited color palette, tasteful dithering, game asset readability",
	"flat-illustration": "flat vector illustration style transformation, clean geometry, minimal shading, bold color blocks, crisp edges, modern editorial design look",
	"candy-cane":        "candy cane style, red and white stripes, christmas theme, sweet, festive decoration",
	"halloween-poster":  "vintage halloween poster style, spooky retro horror mood, dramatic composition, orange-black palette, distressed print texture, high contrast",
	"bangs-filter":      "single person portrait with natural bangs hairstyle, preserve identity, face shape, expression, pose, lighting and background, realistic hair strands, salon quality, high detail",
	"man-filter":        "single person male version of the same subject, preserve identity, facial structure, expression, pose, camera angle, lighting and background, realistic masculine features, natural skin and beard detail, high detail",
	"bald-filter":       "single person portrait with shaved head, preserve identity, expression, pose, lighting and background, realistic scalp texture, natural skin detail, high detail",
	"scream-ai":         "90s slasher movie poster aesthetic, ghostface-inspired horror vibe, dramatic flash lighting, cinematic framing, eerie indoor atmosphere, high detail",
	"y2k-style":         "y2k aesthetic, 2000s futuristic fashion, chrome accents, neon lighting, glossy textures, digital art",
	"3d-caricature":     "stylized 3d caricature portrait, exaggerated but recognizable features, expressive face, polished cg render, soft studio lighting, high detail",
	"16-bit-game":       "retro 16-bit game character art, snes-era pixel style, readable silhouette, limited palette, crisp pixel grid, arcade mood",
	"inverted-face":     "single portrait with intentional inverted or mirrored facial orientation effect, keep identity recognizable, preserve lighting and background, surreal but coherent anatomy",
	"hug-younger-self":  "adult hugging their younger self, both clearly the same identity at different ages, warm emotional moment, natural body interaction, soft nostalgic lighting, high detail",
	"pixie-cut":         "single person portrait with pixie cut hairstyle, preserve identity, face shape, expression, lighting and background, natural hair texture, modern salon finish, high detail",
	"linkedin-photo":    "professional linkedin headshot of the same subject, business attire, confident natural expression, clean neutral background, polished studio lighting, sharp focus, high detail",
	"line-drawing":      "minimalist continuous line drawing style, clean black ink lines on white background, elegant strokes, high contrast, no shading clutter",
	"outpainting":       "seamless image outpainting, expand scene beyond original frame, preserve subject identity and perspective, consistent lighting, color and texture continuity, clean edge blending",
	"emoji-icon":        "emoji-style app icon, bold simple shapes, expressive face, flat vector look, clean edges, centered composition, high legibility on small sizes",
	"hair-style":        "single person hairstyle transformation, preserve identity, face shape and expression, realistic hair texture and strands, salon quality, fashion editorial look, high detail",
	"coloring-page":     "printable coloring book page style, black and white line art, bold clean outlines, empty fill regions, kid-friendly composition, no grayscale shading",
	"artistic-portrait": "fine-art portrait painting style, expressive brushwork, visible canvas texture, rich controlled palette, museum-quality composition, high detail",
	"studio-portrait":   "professional studio portrait of the same subject, controlled key and rim lighting, clean backdrop, natural skin tones, sharp focus, magazine-quality output",
	"baby-face":         "same subject as a toddler-age version, preserve recognizable identity, expression, pose, lighting and background, cute proportions, soft natural skin texture, realistic photography, high detail",
	"3d-figurine":       "stylized 3d figurine of the subject, miniature collectible toy look, clean sculpted details, glossy plastic material, on display base, studio product shot lighting",
	"gta-style":         "gta loading-screen-inspired illustration style, bold outlines, stylized shading, cinematic urban mood, dramatic lighting, poster-quality composition",
}

var LoraNegativePrompts = map[string]string{
	"gender-swap":       "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, two people, extra limbs, extra fingers, plastic skin, over-smoothed skin, text, watermark, logo",
	"90s-camera":        "cgi look, over-sharpened modern phone photo look, clean digital perfection, watermark, logo, text",
	"youtube-thumbnail": "lowres, blurry, dull colors, flat lighting, deformed face, asymmetrical eyes, bad anatomy, duplicate face, messy layout, unreadable text, watermark, logo",
	"pet-meme":          "photo-realistic rendering, lowres, blurry lines, deformed pet face, extra limbs, muddy colors, cluttered background, watermark, logo, text artifacts",
	"watermark-remover": "watermark, logo, text overlay, signature, stamp, compression artifacts, lowres, blurry",
	"manga-color":       "muddy colors, color bleeding outside line art, broken panel lines, inconsistent cel shading, lowres, blurry, text, watermark, logo",
	"santa-hat":         "double hats, malformed hat shape, inconsistent hat perspective, lowres, blurry, text, watermark, logo",
	"old-photo":         "remaining scratches, dust spots, torn-paper artifacts, over-sharpening halos, lowres, blurry, text, watermark, logo",
	"beauty-filter":     "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, extra limbs, extra fingers, waxy skin, over-smoothed skin, text, watermark, logo",
	"ghibsky":           "photorealism, harsh contrast, muddy clouds, noisy sky, lowres, blurry, text, watermark, logo",
	"pixel-art":         "blurry pixels, anti-aliased smooth edges, photorealism, high color noise, lowres, text, watermark, logo",
	"flat-illustration": "photoreal texture, messy gradients, inconsistent vector edges, lowres, blurry, text, watermark, logo",
	"candy-cane":        "irregular stripe pattern, muddy red-white colors, deformed candy shapes, lowres, blurry, text, watermark, logo",
	"halloween-poster":  "cute cheerful mood, weak contrast, modern clean style, lowres, blurry, text glitches, watermark, logo",
	"bangs-filter":      "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, malformed bangs, broken hairline, extra limbs, extra fingers, text, watermark, logo",
	"man-filter":        "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, two people, extra limbs, extra fingers, over-masculinized caricature, text, watermark, logo",
	"bald-filter":       "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, patchy scalp artifacts, extra limbs, extra fingers, text, watermark, logo",
	"scream-ai":         "cute style, bright cheerful mood, low contrast, lowres, blurry, deformed anatomy, text, watermark, logo",
	"y2k-style":         "matte muted palette, photoreal plain look, lowres, blurry, muddy highlights, text, watermark, logo",
	"3d-caricature":     "flat 2d look, lowres, blurry, broken mesh, deformed anatomy, extra limbs, text, watermark, logo",
	"16-bit-game":       "smooth anti-aliased rendering, photorealism, blurry pixels, noisy gradients, lowres, text, watermark, logo",
	"inverted-face":     "normal non-inverted face, broken symmetry artifacts, duplicated eyes, deformed facial proportions, lowres, blurry, text, watermark, logo",
	"hug-younger-self":  "different identities, duplicated adults only, bad hand anatomy, fused bodies, lowres, blurry, text, watermark, logo",
	"linkedin-photo":    "casual messy background, distorted face, harsh shadows, lowres, blurry, text, watermark, logo",
	"line-drawing":      "thick messy strokes, sketch noise, gray wash shading, low contrast lines, lowres, watermark, logo, text",
	"outpainting":       "visible seams, inconsistent perspective, duplicated subject, mismatched lighting, blurry extension, lowres, watermark, logo, text",
	"emoji-icon":        "photoreal style, tiny details, cluttered background, low contrast, lowres, blurry, watermark, logo, text",
	"pixie-cut":         "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, messy cut artifacts, broken hair strands, extra limbs, extra fingers, text, watermark, logo",
	"hair-style":        "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, broken hair strands, unrealistic hair texture, extra limbs, extra fingers, text, watermark, logo",
	"coloring-page":     "grayscale shading, color fills, noisy sketch lines, messy crosshatching, lowres, blurry, text, watermark, logo",
	"artistic-portrait": "flat photo look, weak brush texture, muddy paint strokes, lowres, blurry, text, watermark, logo",
	"studio-portrait":   "busy background clutter, flat lighting, deformed face, lowres, blurry, noise, text, watermark, logo",
	"baby-face":         "lowres, blurry, out of focus, deformed face, asymmetrical eyes, bad anatomy, duplicate face, extra limbs, extra fingers, uncanny proportions, text, watermark, logo",
	"3d-figurine":       "flat 2d look, lowres, blurry, deformed toy proportions, broken base, noisy texture, text, watermark, logo",
	"gta-style":         "photoreal plain photo look, lowres, blurry, weak contrast, deformed anatomy, text, watermark, logo",
}
